// Maps our exercise library's names to a slug in the vendored @bryllim/workout-guide icon set
// (frame-1 PNGs copied into public/exercise-icons/ -- see THIRD_PARTY_NOTICES.md for attribution).
// A handful of near-identical movements intentionally share one slug (e.g. all cable fly variants).
// Names with no entry here just fall back to the generic dumbbell icon; nothing is guessed or faked.
export const EXERCISE_ICON_SLUGS = {
  'Ab Wheel Rollout': 'ab-wheel',
  'Arnold Press': 'arnold-press',
  'Barbell Back Squat': 'squat',
  'Barbell Bench Press': 'bench-press',
  'Barbell Row': 'barbell-row',
  'Bent-Over Rear Delt Raise': 'bent-over-rear-delt-raise',
  'Bicycle Crunch': 'bicycle-crunch',
  'Bulgarian Split Squat': 'bulgarian-split-squat',
  'Cable Crunch': 'cable-crunch',
  'Cable Curl': 'cable-curl',
  'Cable Fly (High to Low)': 'cable-fly',
  'Cable Fly (Low to High)': 'cable-fly',
  'Cable Lateral Raise': 'cable-lateral-raise',
  'Cable Pec Crossover': 'cable-fly',
  'Chest Supported Row': 'chest-supported-row',
  'Chin-Up': 'chin-up',
  'Close-Grip Bench Press': 'close-grip-bench-press',
  'Close-Grip Lat Pulldown': 'close-grip-lat-pulldown',
  'Concentration Curl': 'concentration-curl',
  'Conventional Deadlift': 'deadlift',
  'Dead Bug': 'dead-bug',
  'Decline Barbell Bench Press': 'decline-bench-press',
  'Decline Dumbbell Press': 'decline-dumbbell-press',
  'Deficit Deadlift': 'deadlift',
  'Diamond Push-Up': 'diamond-push-up',
  'Dip (Triceps Focus)': 'dip',
  'Dumbbell Bench Press': 'dumbbell-bench-press',
  'Dumbbell Curl': 'bicep-curl',
  'Dumbbell Fly': 'dumbbell-fly',
  'EZ-Bar Curl': 'ez-bar-curl',
  'Face Pull': 'face-pull',
  'Flat Dumbbell Press': 'dumbbell-bench-press',
  'Front Raise': 'front-raise',
  'Front Squat': 'front-squat',
  'Glute Bridge': 'glute-bridge',
  'Goblet Squat': 'goblet-squat',
  'Good Morning': 'good-morning',
  'Hack Squat': 'hack-squat',
  'Hammer Curl': 'hammer-curl',
  'Hammer Rope Pulley Curl': 'rope-hammer-curl',
  'Hanging Leg Raise': 'hanging-leg-raise',
  'Hip Thrust': 'hip-thrust',
  'Hollow Body Hold': 'hollow-body-hold',
  'Incline Barbell Bench Press': 'incline-bench-press',
  'Incline Dumbbell Curl': 'incline-dumbbell-curl',
  'Incline Dumbbell Press': 'incline-dumbbell-press',
  'Inverted Row': 'inverted-row',
  'Landmine Press': 'landmine-press',
  'Lat Pulldown': 'lat-pulldown',
  'Lateral Raise': 'lateral-raise',
  'Leg Extension': 'leg-extension',
  'Leg Press': 'leg-press',
  'Lying Leg Curl': 'lying-leg-curl',
  'Machine Chest Press': 'machine-chest-press',
  'Machine Row': 'machine-row',
  'Machine Shoulder Press': 'machine-shoulder-press',
  'Meadows Row': 'meadows-row',
  'Mountain Climber': 'mountain-climber',
  'Nordic Hamstring Curl': 'nordic-hamstring-curl',
  'One-Arm Dumbbell Row': 'one-arm-dumbbell-row',
  'Overhead Dumbbell Extension': 'dumbbell-overhead-tricep-extension',
  'Overhead Press': 'overhead-press',
  'Overhead Rope Extension': 'overhead-tricep-extension',
  'Pallof Press': 'pallof-press',
  'Pendlay Barbell Row': 'pendlay-row',
  'Plank': 'plank',
  'Preacher Barbell Curl': 'preacher-curl',
  'Pull-Up': 'pull-up',
  'Push Press': 'push-press',
  'Push-Up': 'push-up',
  'Rack Pull': 'rack-pull',
  'Rear Delt Fly': 'rear-delt-fly',
  'Reverse Curl': 'reverse-curl',
  'Reverse Lunge': 'reverse-lunge',
  'Romanian Deadlift': 'romanian-deadlift',
  'Russian Twist': 'russian-twist',
  'Safety Bar Squat': 'squat',
  'Seated Cable Row': 'seated-row',
  'Seated Calf Raise': 'seated-calf-raise',
  'Seated Dumbbell Shoulder Press': 'seated-dumbbell-press',
  'Seated Leg Curl': 'seated-leg-curl',
  'Side Plank': 'side-plank',
  'Single-Arm Cable Lat Pulldown': 'lat-pulldown',
  'Single-Arm Landmine Press': 'landmine-press',
  'Sissy Squat': 'sissy-squat',
  'Skull Crusher': 'skull-crusher',
  'Smith Machine Bench Press': 'smith-machine-bench-press',
  'Spider Curl': 'spider-curl',
  'Standing Calf Raise': 'standing-calf-raise',
  'Standing Overhead Press': 'overhead-press',
  'Step-Up': 'step-up',
  'Straight-Arm Pulldown': 'straight-arm-pulldown',
  'Sumo Deadlift': 'sumo-deadlift',
  'T-Bar Row': 't-bar-row',
  'Triceps Pushdown': 'tricep-pushdown',
  'Upright Row': 'upright-row',
  'Walking Lunge': 'walking-lunge',
  'Weighted Decline Sit-Up': 'decline-sit-up',
  'Weighted Dips': 'weighted-dip',
  'Weighted Pull-Up': 'weighted-pull-up',
  'Weighted Push-Up': 'weighted-push-up',
  'Wide-Grip Lat Pulldown': 'wide-grip-lat-pulldown',
  'Wrist Curl': 'wrist-curl',
};

export function exerciseIconUrl(name) {
  const slug = EXERCISE_ICON_SLUGS[name];
  return slug ? `/exercise-icons/${slug}.png` : null;
}
