version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "http://127.0.0.1:3000"
      BACKEND_URL: "http://127.0.0.1:4567"
      OTEL_SERVICE_NAME: 'backend_flask'
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      AWS_XRAY_URL: "*127.0.0.1:4567*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"
      ROLLBAR_ACCESS_TOKEN: "${ROLLBAR_ACCESS_TOKEN}"
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_COGNITO_USER_POOL_ID: "eu-central-1_vpiFVQ68P"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "7bn0hbepr945cu3d2ea07btf1p"
      DATABASE_URL: "postgresql://postgres:password@db:5432/cruddur"
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
      - "${HOME}/.aws:/root/.aws:ro"
    depends_on:
      - db

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://127.0.0.1:4567"
      REACT_APP_AWS_PROJECT_REGION: "eu-central-1"
      REACT_APP_AWS_USER_POOLS_ID: "eu-central-1_vpiFVQ68P"
      REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: "7bn0hbepr945cu3d2ea07btf1p"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js

  xray-daemon:
    image: "amazon/aws-xray-daemon"
    volumes:
      - "${HOME}/.aws:/home/xray/.aws:ro"
    entrypoint:
      - "/xray"
    command:
      - "-o"
      - "-t"
      - "0.0.0.0:2000"
      - "-b"
      - "0.0.0.0:2000"
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"

  dynamodb-local:
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data


networks:
  internal-network:
    driver: bridge
    name: cruddur

volumes:
  db:
    driver: local