/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#8083ff',
        'surface-bright': '#373940',
        'on-tertiary': '#3c0091',
        'on-surface-variant': '#c7c4d7',
        'on-background': '#e2e2eb',
        'on-primary-fixed': '#07006c',
        'inverse-surface': '#e2e2eb',
        'inverse-on-surface': '#2e3037',
        'on-secondary': '#003640',
        background: '#111319',
        'inverse-primary': '#494bd6',
        'surface-container-lowest': '#0c0e14',
        'tertiary-fixed-dim': '#d0bcff',
        'surface-container-low': '#191b22',
        'surface-dim': '#111319',
        'outline-variant': '#464554',
        'on-tertiary-fixed': '#23005c',
        secondary: '#4cd7f6',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#5516be',
        'on-secondary-container': '#00424e',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-primary': '#1000a9',
        'tertiary-fixed': '#e9ddff',
        'on-error': '#690005',
        tertiary: '#d0bcff',
        error: '#ffb4ab',
        primary: '#c0c1ff',
        'secondary-container': '#03b5d3',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-error-container': '#ffdad6',
        'on-surface': '#e2e2eb',
        'on-secondary-fixed-variant': '#004e5c',
        'primary-fixed': '#e1e0ff',
        'on-tertiary-container': '#340080',
        'surface-container-highest': '#33343b',
        'surface-variant': '#33343b',
        'surface-container-high': '#282a30',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-container': '#0d0096',
        'surface-tint': '#c0c1ff',
        'surface-container': '#1e1f26',
        'on-secondary-fixed': '#001f26',
        'tertiary-container': '#a078ff',
        outline: '#908fa0',
        surface: '#111319',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'col-feed-max': '620px',
        'space-3xl': '3rem',
        'space-2xs': '0.125rem',
        'space-base': '1rem',
        'space-sm': '0.5rem',
        'col-sidebar-left': '260px',
        'col-sidebar-right': '340px',
        'space-lg': '1.25rem',
        'space-md': '0.75rem',
        'space-2xl': '2rem',
        gutter: '1rem',
        'space-xs': '0.25rem',
        'space-xl': '1.5rem',
      },
      fontFamily: {
        'headline-lg': ['Geist'],
        'headline-md': ['Geist'],
        'label-md': ['Geist'],
        'label-xs': ['Geist'],
        'body-md': ['Geist'],
        'headline-sm': ['Geist'],
        'body-sm': ['Geist'],
        'display-lg': ['Geist'],
        'body-lg': ['Geist'],
        'label-sm': ['Geist'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '500' }],
        'label-xs': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '21px', letterSpacing: '-0.006em', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
